### PR TITLE
FLUID-6524: Migrate to new organisation and update dependencies.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [FLUID-6524](https://issues.fluidproject.org/browse/FLUID-6524) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
@gtirloni, although your tips were enough to get the fluid-couchdb-test-harness CI integration working, the builds still churn and timeout  in this repo.  If you have any ideas I'd appreciate hearing them.

**Comment by gtirloni** [comment]
I'm not familiar with the webdriver (although I should) but it seems to be running things with xfvb-run (Virtual X11 server) instead of having the browser in headless mode. I think that should work nonetheless but I found an action that might help with it: https://github.com/GabrielBB/xvfb-action

**Comment by the-t-in-rtf** [comment]
@gtirloni, the webdriver stack is tested in isolation using the xvfb steps used here ([here's that workflow YAML](https://github.com/fluid-project/fluid-webdriver/blob/master/.github/workflows/main.yml)).

Unfortunately I can't test locally because `act` doesn't seem to provision the required services, if you have ideas there that might also help.  I guess I'll need to pore over the logs, perhaps add logging.

**Comment by the-t-in-rtf** [comment]
So, this is one of the most complex set of tests we have in that:

1. It uses CouchDB (via fluid-couchdb-test-harness).
2. It uses webdriver (via fluid-webdriver).
3. It has to have a test mail server for part of the tests (via fluid-mail-test).

Each of these is tested independently in their respective repos.

**Comment by the-t-in-rtf** [comment]
Rather than hold up the release further, I have filed #9 for the CI integration.

**Comment by the-t-in-rtf** [comment]
@amb26, this should be ready to merge now.  Happy to self-merge.

**Comment by jobara** [comment]
@the-t-in-rtf is there an ETA for when this will be merged and a new release published?

**Comment by the-t-in-rtf** [comment]
Sorry for the lack of follow up.  It's merged and I've cut the `1.0.2` release.

**Comment by jobara** [comment]
@the-t-in-rtf thanks

**Pull request merged**
